name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write       # <-- allows push to branches
  pages: write          # <-- optional (needed if using pages API)
  id-token: write       # <-- optional (needed for pages API auth)

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./public
            keep_files: true             # preserves .github/workflow files
          